### ISSUE TITLE
Traducciones por hacer

### ISSUE THREAD

**Issue by raulwwq0** [raulwwq0/pinia-spanish-docs#1]
- [X] index.md 
- [X] introduction.md 
- [X] getting-started.md
- [X] core-concepts 
  - [X] actions.md
  - [X] getters.md
  - [X] index.md 
  - [X] outside-component-usage.md
  - [X] plugins.md
  - [X] state.md 
- [X] ssr
  - [X] index.md
  - [X] nuxt.md
- [X] cookbook **(thanks to @edgonzalez24)**
  - [X] composables.md
  - [X] composing-stores.md
  - [X] hot-module-replacement
  - [X] index.md
  - [X] migration-0-0-7.md
  - [X] migration-v1-v2.md
  - [X] migration-vuex.md
  - [X] options-api.md
  - [X] testing.md
- [X] api
  - [X] index.md  **(thanks to @edgonzalez24)**
  - [X] enums **(thanks to @edgonzalez24)**
    - [X] pinia.MutationType.md
  - [X] interfaces  **(thanks to @icarusgk)**
    - [X] pinia_testing.TestingOptions.md
    - [X] pinia_testing.TestingPinia.md
    - [X] pinia._StoreOnActionListenerContext.md
    - [X] pinia._StoreWithState.md
    - [X] pinia._SubscriptionCallbackMutationBase.md
    - [X] pinia.DefineSetupStoreOptions.md
    - [X] pinia.DefineStoreOptions.md
    - [X] pinia.DefineStoreOptionsBase.md
    - [X] pinia.DefineStoreOptionsInPlugin.md
    - [X] pinia.MapStoresCustomization.md
    - [X] pinia.Pinia.md
    - [X] pinia.PiniaCustomProperties.md
    - [X] pinia.PiniaCustomStateProperties.md
    - [X] pinia.PiniaPlugin.md
    - [X] pinia.PiniaPluginContext.md
    - [X] pinia.StoreDefinition.md
    - [X] pinia.StoreProperties.md
    - [X] pinia.SubscriptionCallbackMutationDirect.md
    - [X] pinia.SubscriptionCallbackMutationPatchFunction.md
    - [X] pinia.SubscriptionCallbackMutationPatchObject.md
  - [X] modules
    - [X] pinia_nuxt.md
    - [X] pinia_testing.md
    - [X] pinia.md
- [X] Vue components

**Comment by icarusgk** [comment]
Hola, quisiera contribuir a los docs de Pinia en español. La tasks en el issue continuan vacias o se encuentran en en desarrollo local y no se han actualizado con el remote? Porque si es así estaría dispuesto a trabajar en ello a tiempo completo 😄 para asi poder poner la opción de Español en los docs oficiales de Pinia.

**Comment by raulwwq0** [comment]
> Hola, quisiera contribuir a los docs de Pinia en español. La tasks en el issue continuan vacias o se encuentran en en desarrollo local y no se han actualizado con el remote? Porque si es así estaría dispuesto a trabajar en ello a tiempo completo smile para asi poder poner la opción de Español en los docs oficiales de Pinia.

Hola @icarusgk, ahora mismo faltaría por traducir los ficheros de la parte de interfaces de la api. Puedes elegir los archivos que quieras, pero avisame de cuales vas a ir traduciendo para poder ponerlo en este issue. Cuando tengas 2-3 archivos traducidos puedes hacer un PR y alguno de nosotros revisará tus traducciones.

Para cualquier duda puedes preguntarme por [Telegram](https://t.me/raulwwq0) o [Twitter](https://twitter.com/raulwwq0), ya que suelo responder antes. Gracias por querer contribuir :D

**Comment by icarusgk** [comment]
Gracias por la pronta respuesta @raulwwq0 😄 Me parece excelente. Empezaré con los primeros de la sección de interfaces y abriré su correspondiente issue.
